### ISSUE TITLE
Installation failure - "Cannot find SourceControlToken with name GitHub" in deployment step #7

### ISSUE THREAD

**Issue by yokawasa** [shigeyf/ai-digitalmedia#6]
I got the following deployment error in executing deployment step #7

**7. Deploy sample media functions into an Azure Functions account**

- TYPE: Microsoft.Web/sites/sourcecontrols
- RESOURCE ID: /subscriptions/87c7c7f9-0c9f-47d1-a856-1305a0cbfd7a/resourceGroups/RG-aimedia/providers/Microsoft.Web/sites/aimediafuncna22vy36qypii/sourcecontrols/web
- STATUSMESSAGE:
```
{
  "Code": "NotFound",
  "Message": "Cannot find SourceControlToken with name GitHub.",
  "Target": null,
  "Details": [
    {
      "Message": "Cannot find SourceControlToken with name GitHub."
    },
    {
      "Code": "NotFound"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "51004",
        "MessageTemplate": "Cannot find {0} with name {1}.",
        "Parameters": [
          "SourceControlToken",
          "GitHub"
        ],
        "Code": "NotFound",
        "Message": "Cannot find SourceControlToken with name GitHub."
      }
    }
  ],
  "Innererror": null
}
```

Not sure but looks like additional configuration needed prior to #7 ?

**Comment by yokawasa** [comment]
@shigeyf  Can you please take a look

**Comment by shigeyf** [comment]
I have never seen the error before.
Let me check it.
Meanwhile I would ask you to check:
Did you try with your forked repo?

**Comment by yokawasa** [comment]
Yes, I repro this with my forked repo. After I gave Azure ARM/portal to access Github resource, I didn’t see the error anymore. The procedure needed.

**Comment by shigeyf** [comment]
Yes, right. You need to allow Azure Portal to use your Github account token to access Github resources. You will need to add Azure Portal as an Authorized OAuth App in Applications settings of your Github account.
Please confirm if Azure Portal app is registered in your Github Authorized OAuth App in your personal settings of your Github account.
We need to add a documentation to do this registration, since this may not be able to be done in the automation workflow.

**Comment by woeterman94** [comment]
> Yes, right. You need to allow Azure Portal to use your Github account token to access Github resources. You will need to add Azure Portal as an Authorized OAuth App in Applications settings of your Github account. Please confirm if Azure Portal app is registered in your Github Authorized OAuth App in your personal settings of your Github account. We need to add a documentation to do this registration, since this may not be able to be done in the automation workflow.

Any documentation on how to do this?

**Comment by gargabhisar** [comment]
![image](https://user-images.githubusercontent.com/23273356/215345448-4b05ee25-bf71-4380-a3cc-c6b48bdff99b.png)
Its already authorized, I am still getting the same issue.

**Comment by dgsarve** [comment]
Same problem i too facing

**Comment by woeterman94** [comment]
How I did it:

- select external git 
![image](https://user-images.githubusercontent.com/5755057/215724497-5bb55bc1-fa97-4980-9776-a2cbb8478568.png)
- generate a PAT (personal access token) in your Github account. You can do this [here](https://github.com/settings/tokens).
- Enter the repository url in the following format: 
`https://{github-username}:{access-token}@github.com/{organisation-acount}/{repo}.git`

**Comment by gargabhisar** [comment]
![image](https://user-images.githubusercontent.com/23273356/216324427-1052e5ef-3533-4722-8099-9066c7765094.png)
I am not getting "GITHUB External" Option in API App Service.

**Comment by mak-thevar** [comment]
This error occurs due to connecting Github to multiple Azure accounts. To resolve it, simply revoke all Azure-related apps from the "Authorized OAuth Apps" section in Github settings (https://github.com/settings/applications), then re-authorize Github in Azure. This should allow you to save the deployment.

**Comment by MikaVirkkunen** [comment]
Same problem for me. If I revoke all OAuth apps and try to create the connection through Deployment Center under Functions App it adds the Azure App Service as Authorized OAuth App but portal still gives the error: "Failed to set up deployment: Cannot find SourceControlToken with name GitHub."

**Comment by anttikarjalainen** [comment]
@MikaVirkkunen I got it working by disconnecting the github account from deployment center, then opened up the destination (wwwroot/site) in ftps(I used WinScp), transfered some files there and deleted them. Then afterwards I authorized through git and it started working. No idea what happened.

**Comment by ph1l1pF** [comment]
I tried it with another browser and then it worked. Seems to be a browser caching problem

**Comment by JulianDeal** [comment]
> I tried it with another browser and then it worked. Seems to be a browser caching problem

I can confirm that deleting the browser cache solves the problem.

**Comment by SIYEA0405** [comment]
I deleting the browser cache solves the problem.

**Comment by paulious83** [comment]
I had azure and git running in chrome but noticed when you select in the development centre to authorize it will load an edge browser window. 

closed everything down and restarted the process from Edge and it took two attempts but worked

**Comment by Leader254** [comment]
I am getting the same error here

**Comment by vpallathu** [comment]
I'm getting this error from the template that I generated from Azure for creating ```Function App``` resources. I cleared the cookies which did not help. I posted the error in [stackoverflow](https://stackoverflow.com/questions/76729939/how-to-configure-deployment-center-configuration-in-arm-template). I'm using ```Service Principal``` to create ```Function App``` resources.
